package com.mymoss.learnlist.data.local

import androidx.room.Entity
import androidx.room.Index
import androidx.room.ColumnInfo

@Entity(
    tableName = "projects",
    indices = [Index("isArchived"), Index("deletedAt"), Index("updatedAt")],
)
data class ProjectEntity(
    @androidx.room.PrimaryKey val id: String,
    val title: String,
    val type: String,
    val description: String,
    val tagCsv: String,
    val colorHex: String,
    val isArchived: Boolean,
    val isPaused: Boolean,
    val createdAt: Long,
    val updatedAt: Long,
    val deletedAt: Long? = null,
)

@Entity(
    tableName = "learning_tasks",
    indices = [Index("projectId"), Index("nextReviewDate"), Index("isArchived"), Index("deletedAt")],
)
data class LearningTaskEntity(
    @androidx.room.PrimaryKey val id: String,
    val projectId: String,
    val title: String,
    val prompt: String,
    val notes: String,
    val source: String,
    val isRequired: Boolean,
    val isArchived: Boolean,
    val hasLearned: Boolean,
    val initialLearningDate: String?,
    val stage: Int,
    val nextReviewDate: String?,
    val snoozedUntil: String?,
    val createdAt: Long,
    val updatedAt: Long,
    val deletedAt: Long? = null,
)

@Entity(
    tableName = "review_logs",
    indices = [Index("taskId"), Index("reviewedOn")],
)
data class ReviewLogEntity(
    @androidx.room.PrimaryKey val id: String,
    val taskId: String,
    val rating: String,
    val reviewedOn: String,
    val previousStage: Int,
    val nextStage: Int,
    val nextReviewDate: String,
    val createdAt: Long,
)

@Entity(
    tableName = "review_corrections",
    indices = [Index("taskId"), Index("createdAt")],
)
data class ReviewCorrectionEntity(
    @androidx.room.PrimaryKey val id: String,
    val taskId: String,
    val correctedStage: Int,
    val correctedNextReviewDate: String,
    val reason: String,
    val createdAt: Long,
)

@Entity(
    tableName = "reading_plans",
    indices = [Index("projectId"), Index("isArchived"), Index("deletedAt")],
)
data class ReadingPlanEntity(
    @androidx.room.PrimaryKey val id: String,
    val projectId: String,
    val title: String,
    val totalPages: Int,
    val dailyTarget: Int,
    val currentPage: Int,
    val startDate: String,
    val deadline: String?,
    val isPaused: Boolean,
    val isArchived: Boolean,
    val createdAt: Long,
    val updatedAt: Long,
    val deletedAt: Long? = null,
)

/** A dated target generated by catch-up rebalancing or adjusted manually. */
@Entity(
    tableName = "reading_targets",
    indices = [Index(value = ["planId", "localDate"], unique = true)],
)
data class ReadingTargetEntity(
    @androidx.room.PrimaryKey val id: String,
    val planId: String,
    val localDate: String,
    val targetPages: Int,
    val updatedAt: Long,
)

@Entity(
    tableName = "page_logs",
    indices = [Index("planId"), Index("localDate")],
)
data class PageLogEntity(
    @androidx.room.PrimaryKey val id: String,
    val planId: String,
    val localDate: String,
    val pagesRead: Int,
    val startPage: Int?,
    val endPage: Int?,
    val createdAt: Long,
)

@Entity(
    tableName = "reading_adjustments",
    indices = [Index("planId"), Index("localDate"), Index("createdAt")],
)
data class ReadingAdjustmentEntity(
    @androidx.room.PrimaryKey val id: String,
    val planId: String,
    val localDate: String,
    val deltaPages: Int,
    val reason: String,
    val createdAt: Long,
)

@Entity(
    tableName = "todos",
    indices = [Index("dueDate"), Index("projectId"), Index("isArchived"), Index("deletedAt"), Index("repeatRule"), Index("recurrenceSourceId")],
)
data class TodoEntity(
    @androidx.room.PrimaryKey val id: String,
    val title: String,
    val notes: String,
    val isRequired: Boolean,
    val repeatRule: String,
    val customRepeatDays: String,
    val dueDate: String?,
    val completedDates: String,
    val isArchived: Boolean,
    val createdAt: Long,
    val updatedAt: Long,
    val projectId: String? = null,
    val deletedAt: Long? = null,
    /** One-off instance created from a missed recurring todo. */
    val recurrenceSourceId: String? = null,
    val missedPromptPolicy: String = "ASK",
)

@Entity(
    tableName = "focus_sessions",
    indices = [Index("startedAt"), Index("projectId")],
)
data class FocusSessionEntity(
    @androidx.room.PrimaryKey val id: String,
    val projectId: String?,
    val taskId: String?,
    val startedAt: Long,
    val endedAt: Long?,
    val plannedMinutes: Int,
    val actualMinutes: Int,
    val status: String,
    @ColumnInfo(defaultValue = "0") val actualSeconds: Int = actualMinutes * 60,
    @ColumnInfo(defaultValue = "'WORK'") val phase: String = "WORK",
    @ColumnInfo(defaultValue = "1") val round: Int = 1,
)

@Entity(
    tableName = "goals",
    indices = [Index("isArchived"), Index("deletedAt"), Index("endDate")],
)
data class GoalEntity(
    @androidx.room.PrimaryKey val id: String,
    val title: String,
    val metric: String,
    val targetValue: Int,
    val period: String,
    val startDate: String,
    val endDate: String?,
    val projectId: String?,
    val isArchived: Boolean,
    val createdAt: Long,
    val updatedAt: Long,
    val deletedAt: Long? = null,
)

@Entity(
    tableName = "countdowns",
    indices = [Index("eventAtEpochMillis"), Index("isArchived"), Index("deletedAt")],
)
data class CountdownEntity(
    @androidx.room.PrimaryKey val id: String,
    val title: String,
    val note: String,
    val eventAtEpochMillis: Long,
    val reminderMinutesBefore: Int?,
    val isCompleted: Boolean,
    val isArchived: Boolean,
    val createdAt: Long,
    val updatedAt: Long,
    val deletedAt: Long? = null,
)

@Entity(
    tableName = "reminders",
    indices = [Index("projectId"), Index("enabled")],
)
data class ReminderEntity(
    @androidx.room.PrimaryKey val id: String,
    val projectId: String?,
    val kind: String,
    val timeMinutes: Int,
    val repeatDays: String,
    val enabled: Boolean,
    val quietStartMinutes: Int?,
    val quietEndMinutes: Int?,
    val createdAt: Long,
    val updatedAt: Long,
)
